/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageStyle } from './ImageStyle';
import {
    ImageStyleFromJSON,
    ImageStyleFromJSONTyped,
    ImageStyleToJSON,
    ImageStyleToJSONTyped,
} from './ImageStyle';
import type { ImageSubStyle } from './ImageSubStyle';
import {
    ImageSubStyleFromJSON,
    ImageSubStyleFromJSONTyped,
    ImageSubStyleToJSON,
    ImageSubStyleToJSONTyped,
} from './ImageSubStyle';

/**
 * 
 * @export
 * @interface CreateStyleResponse
 */
export interface CreateStyleResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateStyleResponse
     */
    creationTime: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStyleResponse
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateStyleResponse
     */
    isPrivate: boolean;
    /**
     * 
     * @type {ImageStyle}
     * @memberof CreateStyleResponse
     */
    style: ImageStyle;
    /**
     * 
     * @type {ImageSubStyle}
     * @memberof CreateStyleResponse
     */
    substyle?: ImageSubStyle;
    /**
     * 
     * @type {number}
     * @memberof CreateStyleResponse
     */
    credits: number;
}



/**
 * Check if a given object implements the CreateStyleResponse interface.
 */
export function instanceOfCreateStyleResponse(value: object): value is CreateStyleResponse {
    if (!('creationTime' in value) || value['creationTime'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isPrivate' in value) || value['isPrivate'] === undefined) return false;
    if (!('style' in value) || value['style'] === undefined) return false;
    if (!('credits' in value) || value['credits'] === undefined) return false;
    return true;
}

export function CreateStyleResponseFromJSON(json: any): CreateStyleResponse {
    return CreateStyleResponseFromJSONTyped(json, false);
}

export function CreateStyleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStyleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'creationTime': json['creation_time'],
        'id': json['id'],
        'isPrivate': json['is_private'],
        'style': ImageStyleFromJSON(json['style']),
        'substyle': json['substyle'] == null ? undefined : ImageSubStyleFromJSON(json['substyle']),
        'credits': json['credits'],
    };
}

export function CreateStyleResponseToJSON(json: any): CreateStyleResponse {
    return CreateStyleResponseToJSONTyped(json, false);
}

export function CreateStyleResponseToJSONTyped(value?: CreateStyleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creation_time': value['creationTime'],
        'id': value['id'],
        'is_private': value['isPrivate'],
        'style': ImageStyleToJSON(value['style']),
        'substyle': ImageSubStyleToJSON(value['substyle']),
        'credits': value['credits'],
    };
}

