/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DescribeImageRequest
 */
export interface DescribeImageRequest {
    /**
     * 
     * @type {Blob}
     * @memberof DescribeImageRequest
     */
    image: Blob;
}

/**
 * Check if a given object implements the DescribeImageRequest interface.
 */
export function instanceOfDescribeImageRequest(value: object): value is DescribeImageRequest {
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function DescribeImageRequestFromJSON(json: any): DescribeImageRequest {
    return DescribeImageRequestFromJSONTyped(json, false);
}

export function DescribeImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DescribeImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
    };
}

export function DescribeImageRequestToJSON(json: any): DescribeImageRequest {
    return DescribeImageRequestToJSONTyped(json, false);
}

export function DescribeImageRequestToJSONTyped(value?: DescribeImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
    };
}

