/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DescribeImageResponse
 */
export interface DescribeImageResponse {
    /**
     * 
     * @type {string}
     * @memberof DescribeImageResponse
     */
    caption: string;
    /**
     * 
     * @type {number}
     * @memberof DescribeImageResponse
     */
    credits: number;
}

/**
 * Check if a given object implements the DescribeImageResponse interface.
 */
export function instanceOfDescribeImageResponse(value: object): value is DescribeImageResponse {
    if (!('caption' in value) || value['caption'] === undefined) return false;
    if (!('credits' in value) || value['credits'] === undefined) return false;
    return true;
}

export function DescribeImageResponseFromJSON(json: any): DescribeImageResponse {
    return DescribeImageResponseFromJSONTyped(json, false);
}

export function DescribeImageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DescribeImageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'caption': json['caption'],
        'credits': json['credits'],
    };
}

export function DescribeImageResponseToJSON(json: any): DescribeImageResponse {
    return DescribeImageResponseToJSONTyped(json, false);
}

export function DescribeImageResponseToJSONTyped(value?: DescribeImageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'caption': value['caption'],
        'credits': value['credits'],
    };
}

