/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseFormat } from './ResponseFormat';
import {
    ResponseFormatFromJSON,
    ResponseFormatFromJSONTyped,
    ResponseFormatToJSON,
    ResponseFormatToJSONTyped,
} from './ResponseFormat';
import type { TextLayoutItem } from './TextLayoutItem';
import {
    TextLayoutItemFromJSON,
    TextLayoutItemFromJSONTyped,
    TextLayoutItemToJSON,
    TextLayoutItemToJSONTyped,
} from './TextLayoutItem';
import type { TransformModel } from './TransformModel';
import {
    TransformModelFromJSON,
    TransformModelFromJSONTyped,
    TransformModelToJSON,
    TransformModelToJSONTyped,
} from './TransformModel';
import type { ImageSize } from './ImageSize';
import {
    ImageSizeFromJSON,
    ImageSizeFromJSONTyped,
    ImageSizeToJSON,
    ImageSizeToJSONTyped,
} from './ImageSize';
import type { UserControls } from './UserControls';
import {
    UserControlsFromJSON,
    UserControlsFromJSONTyped,
    UserControlsToJSON,
    UserControlsToJSONTyped,
} from './UserControls';
import type { ImageStyle } from './ImageStyle';
import {
    ImageStyleFromJSON,
    ImageStyleFromJSONTyped,
    ImageStyleToJSON,
    ImageStyleToJSONTyped,
} from './ImageStyle';
import type { ImageSubStyle } from './ImageSubStyle';
import {
    ImageSubStyleFromJSON,
    ImageSubStyleFromJSONTyped,
    ImageSubStyleToJSON,
    ImageSubStyleToJSONTyped,
} from './ImageSubStyle';
import type { ImageFormat } from './ImageFormat';
import {
    ImageFormatFromJSON,
    ImageFormatFromJSONTyped,
    ImageFormatToJSON,
    ImageFormatToJSONTyped,
} from './ImageFormat';

/**
 * 
 * @export
 * @interface GenerateImageRequest
 */
export interface GenerateImageRequest {
    /**
     * 
     * @type {string}
     * @memberof GenerateImageRequest
     */
    prompt: string;
    /**
     * 
     * @type {number}
     * @memberof GenerateImageRequest
     */
    n?: number;
    /**
     * 
     * @type {ResponseFormat}
     * @memberof GenerateImageRequest
     */
    responseFormat?: ResponseFormat;
    /**
     * 
     * @type {ImageFormat}
     * @memberof GenerateImageRequest
     */
    imageFormat?: ImageFormat;
    /**
     * 
     * @type {ImageSize}
     * @memberof GenerateImageRequest
     */
    size?: ImageSize;
    /**
     * 
     * @type {string}
     * @memberof GenerateImageRequest
     */
    styleId?: string;
    /**
     * 
     * @type {ImageStyle}
     * @memberof GenerateImageRequest
     */
    style?: ImageStyle;
    /**
     * 
     * @type {ImageSubStyle}
     * @memberof GenerateImageRequest
     */
    substyle?: ImageSubStyle;
    /**
     * 
     * @type {UserControls}
     * @memberof GenerateImageRequest
     */
    controls?: UserControls;
    /**
     * 
     * @type {TransformModel}
     * @memberof GenerateImageRequest
     */
    model?: TransformModel;
    /**
     * 
     * @type {number}
     * @memberof GenerateImageRequest
     */
    randomSeed?: number;
    /**
     * 
     * @type {Array<TextLayoutItem>}
     * @memberof GenerateImageRequest
     */
    textLayout?: Array<TextLayoutItem>;
    /**
     * 
     * @type {boolean}
     * @memberof GenerateImageRequest
     */
    blockNsfw?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GenerateImageRequest
     */
    calculateFeatures?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GenerateImageRequest
     */
    negativePrompt?: string;
}



/**
 * Check if a given object implements the GenerateImageRequest interface.
 */
export function instanceOfGenerateImageRequest(value: object): value is GenerateImageRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function GenerateImageRequestFromJSON(json: any): GenerateImageRequest {
    return GenerateImageRequestFromJSONTyped(json, false);
}

export function GenerateImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'n': json['n'] == null ? undefined : json['n'],
        'responseFormat': json['response_format'] == null ? undefined : ResponseFormatFromJSON(json['response_format']),
        'imageFormat': json['image_format'] == null ? undefined : ImageFormatFromJSON(json['image_format']),
        'size': json['size'] == null ? undefined : ImageSizeFromJSON(json['size']),
        'styleId': json['style_id'] == null ? undefined : json['style_id'],
        'style': json['style'] == null ? undefined : ImageStyleFromJSON(json['style']),
        'substyle': json['substyle'] == null ? undefined : ImageSubStyleFromJSON(json['substyle']),
        'controls': json['controls'] == null ? undefined : UserControlsFromJSON(json['controls']),
        'model': json['model'] == null ? undefined : TransformModelFromJSON(json['model']),
        'randomSeed': json['random_seed'] == null ? undefined : json['random_seed'],
        'textLayout': json['text_layout'] == null ? undefined : ((json['text_layout'] as Array<any>).map(TextLayoutItemFromJSON)),
        'blockNsfw': json['block_nsfw'] == null ? undefined : json['block_nsfw'],
        'calculateFeatures': json['calculate_features'] == null ? undefined : json['calculate_features'],
        'negativePrompt': json['negative_prompt'] == null ? undefined : json['negative_prompt'],
    };
}

export function GenerateImageRequestToJSON(json: any): GenerateImageRequest {
    return GenerateImageRequestToJSONTyped(json, false);
}

export function GenerateImageRequestToJSONTyped(value?: GenerateImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'n': value['n'],
        'response_format': ResponseFormatToJSON(value['responseFormat']),
        'image_format': ImageFormatToJSON(value['imageFormat']),
        'size': ImageSizeToJSON(value['size']),
        'style_id': value['styleId'],
        'style': ImageStyleToJSON(value['style']),
        'substyle': ImageSubStyleToJSON(value['substyle']),
        'controls': UserControlsToJSON(value['controls']),
        'model': TransformModelToJSON(value['model']),
        'random_seed': value['randomSeed'],
        'text_layout': value['textLayout'] == null ? undefined : ((value['textLayout'] as Array<any>).map(TextLayoutItemToJSON)),
        'block_nsfw': value['blockNsfw'],
        'calculate_features': value['calculateFeatures'],
        'negative_prompt': value['negativePrompt'],
    };
}

