/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
    ImageToJSONTyped,
} from './Image';

/**
 * 
 * @export
 * @interface GenerateImageResponse
 */
export interface GenerateImageResponse {
    /**
     * 
     * @type {number}
     * @memberof GenerateImageResponse
     */
    created: number;
    /**
     * 
     * @type {number}
     * @memberof GenerateImageResponse
     */
    credits: number;
    /**
     * 
     * @type {Array<Image>}
     * @memberof GenerateImageResponse
     */
    data: Array<Image>;
}

/**
 * Check if a given object implements the GenerateImageResponse interface.
 */
export function instanceOfGenerateImageResponse(value: object): value is GenerateImageResponse {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('credits' in value) || value['credits'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GenerateImageResponseFromJSON(json: any): GenerateImageResponse {
    return GenerateImageResponseFromJSONTyped(json, false);
}

export function GenerateImageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateImageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'],
        'credits': json['credits'],
        'data': ((json['data'] as Array<any>).map(ImageFromJSON)),
    };
}

export function GenerateImageResponseToJSON(json: any): GenerateImageResponse {
    return GenerateImageResponseToJSONTyped(json, false);
}

export function GenerateImageResponseToJSONTyped(value?: GenerateImageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'credits': value['credits'],
        'data': ((value['data'] as Array<any>).map(ImageToJSON)),
    };
}

