/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageColor
 */
export interface ImageColor {
    /**
     * 
     * @type {Array<number>}
     * @memberof ImageColor
     */
    rgb?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ImageColor
     */
    std?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof ImageColor
     */
    weight?: number;
}

/**
 * Check if a given object implements the ImageColor interface.
 */
export function instanceOfImageColor(value: object): value is ImageColor {
    return true;
}

export function ImageColorFromJSON(json: any): ImageColor {
    return ImageColorFromJSONTyped(json, false);
}

export function ImageColorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageColor {
    if (json == null) {
        return json;
    }
    return {
        
        'rgb': json['rgb'] == null ? undefined : json['rgb'],
        'std': json['std'] == null ? undefined : json['std'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function ImageColorToJSON(json: any): ImageColor {
    return ImageColorToJSONTyped(json, false);
}

export function ImageColorToJSONTyped(value?: ImageColor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rgb': value['rgb'],
        'std': value['std'],
        'weight': value['weight'],
    };
}

