/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ImageSubStyle = {
    _2dArtPoster: '2d_art_poster',
    _3d: '3d',
    _80s: '80s',
    Glow: 'glow',
    Grain: 'grain',
    HandDrawn: 'hand_drawn',
    InfantileSketch: 'infantile_sketch',
    Kawaii: 'kawaii',
    PixelArt: 'pixel_art',
    Psychedelic: 'psychedelic',
    Seamless: 'seamless',
    Voxel: 'voxel',
    Watercolor: 'watercolor',
    BrokenLine: 'broken_line',
    ColoredOutline: 'colored_outline',
    ColoredShapes: 'colored_shapes',
    ColoredShapesGradient: 'colored_shapes_gradient',
    DoodleFill: 'doodle_fill',
    DoodleOffsetFill: 'doodle_offset_fill',
    OffsetFill: 'offset_fill',
    Outline: 'outline',
    OutlineGradient: 'outline_gradient',
    UnevenFill: 'uneven_fill',
    _70s: '70s',
    Cartoon: 'cartoon',
    DoodleLineArt: 'doodle_line_art',
    Engraving: 'engraving',
    Flat2: 'flat_2',
    Kawaii2: 'kawaii',
    LineArt: 'line_art',
    Linocut: 'linocut',
    Seamless2: 'seamless',
    BAndW: 'b_and_w',
    Enterprise: 'enterprise',
    HardFlash: 'hard_flash',
    Hdr: 'hdr',
    MotionBlur: 'motion_blur',
    NaturalLight: 'natural_light',
    StudioPortrait: 'studio_portrait',
    LineCircuit: 'line_circuit',
    _2dArtPoster2: '2d_art_poster_2',
    EngravingColor: 'engraving_color',
    FlatAirArt: 'flat_air_art',
    HandDrawnOutline: 'hand_drawn_outline',
    Handmade3d: 'handmade_3d',
    StickersDrawings: 'stickers_drawings',
    Plastic: 'plastic',
    Pictogram: 'pictogram'
} as const;
export type ImageSubStyle = typeof ImageSubStyle[keyof typeof ImageSubStyle];


export function instanceOfImageSubStyle(value: any): boolean {
    for (const key in ImageSubStyle) {
        if (Object.prototype.hasOwnProperty.call(ImageSubStyle, key)) {
            if (ImageSubStyle[key as keyof typeof ImageSubStyle] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ImageSubStyleFromJSON(json: any): ImageSubStyle {
    return ImageSubStyleFromJSONTyped(json, false);
}

export function ImageSubStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageSubStyle {
    return json as ImageSubStyle;
}

export function ImageSubStyleToJSON(value?: ImageSubStyle | null): any {
    return value as any;
}

export function ImageSubStyleToJSONTyped(value: any, ignoreDiscriminator: boolean): ImageSubStyle {
    return value as ImageSubStyle;
}

