/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ImageSize = {
    _1024x1024: '1024x1024',
    _1365x1024: '1365x1024',
    _1024x1365: '1024x1365',
    _1536x1024: '1536x1024',
    _1024x1536: '1024x1536',
    _1820x1024: '1820x1024',
    _1024x1820: '1024x1820',
    _1024x2048: '1024x2048',
    _2048x1024: '2048x1024',
    _1434x1024: '1434x1024',
    _1024x1434: '1024x1434',
    _1024x1280: '1024x1280',
    _1280x1024: '1280x1024',
    _1024x1707: '1024x1707',
    _1707x1024: '1707x1024'
} as const;
export type ImageSize = typeof ImageSize[keyof typeof ImageSize];


export function instanceOfImageSize(value: any): boolean {
    for (const key in ImageSize) {
        if (Object.prototype.hasOwnProperty.call(ImageSize, key)) {
            if (ImageSize[key as keyof typeof ImageSize] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ImageSizeFromJSON(json: any): ImageSize {
    return ImageSizeFromJSONTyped(json, false);
}

export function ImageSizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageSize {
    return json as ImageSize;
}

export function ImageSizeToJSON(value?: ImageSize | null): any {
    return value as any;
}

export function ImageSizeToJSONTyped(value: any, ignoreDiscriminator: boolean): ImageSize {
    return value as ImageSize;
}

