/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ImageStyle = {
    DigitalIllustration: 'digital_illustration',
    Icon: 'icon',
    RealisticImage: 'realistic_image',
    VectorIllustration: 'vector_illustration'
} as const;
export type ImageStyle = typeof ImageStyle[keyof typeof ImageStyle];


export function instanceOfImageStyle(value: any): boolean {
    for (const key in ImageStyle) {
        if (Object.prototype.hasOwnProperty.call(ImageStyle, key)) {
            if (ImageStyle[key as keyof typeof ImageStyle] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ImageStyleFromJSON(json: any): ImageStyle {
    return ImageStyleFromJSONTyped(json, false);
}

export function ImageStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageStyle {
    return json as ImageStyle;
}

export function ImageStyleToJSON(value?: ImageStyle | null): any {
    return value as any;
}

export function ImageStyleToJSONTyped(value: any, ignoreDiscriminator: boolean): ImageStyle {
    return value as ImageStyle;
}

