/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BasicStyle } from './BasicStyle';
import {
    BasicStyleFromJSON,
    BasicStyleFromJSONTyped,
    BasicStyleToJSON,
    BasicStyleToJSONTyped,
} from './BasicStyle';

/**
 * 
 * @export
 * @interface ListBasicStylesResponse
 */
export interface ListBasicStylesResponse {
    /**
     * 
     * @type {Array<BasicStyle>}
     * @memberof ListBasicStylesResponse
     */
    styles: Array<BasicStyle>;
}

/**
 * Check if a given object implements the ListBasicStylesResponse interface.
 */
export function instanceOfListBasicStylesResponse(value: object): value is ListBasicStylesResponse {
    if (!('styles' in value) || value['styles'] === undefined) return false;
    return true;
}

export function ListBasicStylesResponseFromJSON(json: any): ListBasicStylesResponse {
    return ListBasicStylesResponseFromJSONTyped(json, false);
}

export function ListBasicStylesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBasicStylesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'styles': ((json['styles'] as Array<any>).map(BasicStyleFromJSON)),
    };
}

export function ListBasicStylesResponseToJSON(json: any): ListBasicStylesResponse {
    return ListBasicStylesResponseToJSONTyped(json, false);
}

export function ListBasicStylesResponseToJSONTyped(value?: ListBasicStylesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'styles': ((value['styles'] as Array<any>).map(BasicStyleToJSON)),
    };
}

