/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Style } from './Style';
import {
    StyleFromJSON,
    StyleFromJSONTyped,
    StyleToJSON,
    StyleToJSONTyped,
} from './Style';

/**
 * 
 * @export
 * @interface ListStylesResponse
 */
export interface ListStylesResponse {
    /**
     * 
     * @type {Array<Style>}
     * @memberof ListStylesResponse
     */
    styles: Array<Style>;
}

/**
 * Check if a given object implements the ListStylesResponse interface.
 */
export function instanceOfListStylesResponse(value: object): value is ListStylesResponse {
    if (!('styles' in value) || value['styles'] === undefined) return false;
    return true;
}

export function ListStylesResponseFromJSON(json: any): ListStylesResponse {
    return ListStylesResponseFromJSONTyped(json, false);
}

export function ListStylesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListStylesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'styles': ((json['styles'] as Array<any>).map(StyleFromJSON)),
    };
}

export function ListStylesResponseToJSON(json: any): ListStylesResponse {
    return ListStylesResponseToJSONTyped(json, false);
}

export function ListStylesResponseToJSONTyped(value?: ListStylesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'styles': ((value['styles'] as Array<any>).map(StyleToJSON)),
    };
}

