/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
    ImageToJSONTyped,
} from './Image';

/**
 * 
 * @export
 * @interface ProcessImageResponse
 */
export interface ProcessImageResponse {
    /**
     * 
     * @type {number}
     * @memberof ProcessImageResponse
     */
    created: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessImageResponse
     */
    credits: number;
    /**
     * 
     * @type {Image}
     * @memberof ProcessImageResponse
     */
    image: Image;
}

/**
 * Check if a given object implements the ProcessImageResponse interface.
 */
export function instanceOfProcessImageResponse(value: object): value is ProcessImageResponse {
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('credits' in value) || value['credits'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function ProcessImageResponseFromJSON(json: any): ProcessImageResponse {
    return ProcessImageResponseFromJSONTyped(json, false);
}

export function ProcessImageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessImageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'],
        'credits': json['credits'],
        'image': ImageFromJSON(json['image']),
    };
}

export function ProcessImageResponseToJSON(json: any): ProcessImageResponse {
    return ProcessImageResponseToJSONTyped(json, false);
}

export function ProcessImageResponseToJSONTyped(value?: ProcessImageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'credits': value['credits'],
        'image': ImageToJSON(value['image']),
    };
}

