/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ResponseFormat = {
    Url: 'url',
    B64Json: 'b64_json'
} as const;
export type ResponseFormat = typeof ResponseFormat[keyof typeof ResponseFormat];


export function instanceOfResponseFormat(value: any): boolean {
    for (const key in ResponseFormat) {
        if (Object.prototype.hasOwnProperty.call(ResponseFormat, key)) {
            if (ResponseFormat[key as keyof typeof ResponseFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResponseFormatFromJSON(json: any): ResponseFormat {
    return ResponseFormatFromJSONTyped(json, false);
}

export function ResponseFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseFormat {
    return json as ResponseFormat;
}

export function ResponseFormatToJSON(value?: ResponseFormat | null): any {
    return value as any;
}

export function ResponseFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): ResponseFormat {
    return value as ResponseFormat;
}

