/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemStatus
 */
export interface SystemStatus {
    /**
     * 
     * @type {boolean}
     * @memberof SystemStatus
     */
    generation: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SystemStatus
     */
    service: boolean;
}

/**
 * Check if a given object implements the SystemStatus interface.
 */
export function instanceOfSystemStatus(value: object): value is SystemStatus {
    if (!('generation' in value) || value['generation'] === undefined) return false;
    if (!('service' in value) || value['service'] === undefined) return false;
    return true;
}

export function SystemStatusFromJSON(json: any): SystemStatus {
    return SystemStatusFromJSONTyped(json, false);
}

export function SystemStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'generation': json['generation'],
        'service': json['service'],
    };
}

export function SystemStatusToJSON(json: any): SystemStatus {
    return SystemStatusToJSONTyped(json, false);
}

export function SystemStatusToJSONTyped(value?: SystemStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generation': value['generation'],
        'service': value['service'],
    };
}

