/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextLayoutItem
 */
export interface TextLayoutItem {
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof TextLayoutItem
     */
    bbox: Array<Array<number>>;
    /**
     * 
     * @type {string}
     * @memberof TextLayoutItem
     */
    text: string;
}

/**
 * Check if a given object implements the TextLayoutItem interface.
 */
export function instanceOfTextLayoutItem(value: object): value is TextLayoutItem {
    if (!('bbox' in value) || value['bbox'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function TextLayoutItemFromJSON(json: any): TextLayoutItem {
    return TextLayoutItemFromJSONTyped(json, false);
}

export function TextLayoutItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextLayoutItem {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'],
        'text': json['text'],
    };
}

export function TextLayoutItemToJSON(json: any): TextLayoutItem {
    return TextLayoutItemToJSONTyped(json, false);
}

export function TextLayoutItemToJSONTyped(value?: TextLayoutItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': value['bbox'],
        'text': value['text'],
    };
}

