/* tslint:disable */
/* eslint-disable */
/**
 * recraft.ai external api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TransformModel = {
    Refm1: 'refm1',
    Recraft20b: 'recraft20b',
    Recraftv2: 'recraftv2',
    Recraftv3: 'recraftv3',
    Flux1KontextPro: 'flux1_kontext_pro',
    Flux1KontextMax: 'flux1_kontext_max',
    Flux11pro: 'flux1_1pro',
    Flux1dev: 'flux1dev',
    Imagen3: 'imagen3',
    Imagen4: 'imagen4',
    Imagen4Ultra: 'imagen4_ultra',
    HidreamI1Dev: 'hidream_i1_dev',
    GptImage1Low: 'gpt_image_1_low',
    GptImage1Medium: 'gpt_image_1_medium',
    GptImage1High: 'gpt_image_1_high'
} as const;
export type TransformModel = typeof TransformModel[keyof typeof TransformModel];


export function instanceOfTransformModel(value: any): boolean {
    for (const key in TransformModel) {
        if (Object.prototype.hasOwnProperty.call(TransformModel, key)) {
            if (TransformModel[key as keyof typeof TransformModel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TransformModelFromJSON(json: any): TransformModel {
    return TransformModelFromJSONTyped(json, false);
}

export function TransformModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransformModel {
    return json as TransformModel;
}

export function TransformModelToJSON(value?: TransformModel | null): any {
    return value as any;
}

export function TransformModelToJSONTyped(value: any, ignoreDiscriminator: boolean): TransformModel {
    return value as TransformModel;
}

