name: publish-on-tag

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      npm_config_cpu: wasm32

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm run build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          NAME=$(node -p "require('./package.json').name")
          VERSION=$(node -p "require('./package.json').version")

          echo "Package $NAME version $VERSION"

          if npm view "$NAME@$VERSION" version >/dev/null 2>&1; then
            echo "Version already published – skipping."
            exit 0
          fi

          npm publish --access public

      - name: Build .dxt
        run: |
          npm i -g @anthropic-ai/dxt
          BASENAME=$(node -p "require('./package.json').name.split('/').pop()")
          VERSION=${GITHUB_REF#refs/tags/v}
          dxt pack . "dist/$BASENAME-$VERSION.dxt"

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*.dxt
          generate_release_notes: true
