name: release-please
on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: .github/workflows/configs/release-please-config.json
          manifest-file: .github/workflows/configs/.release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}
